### ISSUE TITLE
Add a main technical contact on contact page

### ISSUE THREAD

**Issue by susheel** [ga4gh-beacon/ga4gh-beacon-legacy-website#10]

**Comment by mbaudis** [comment]
I suggest https://github.com/ga4gh-beacon/ga4gh-beacon.github.io/pull/12 , and going from there:

* remove the separate `Developers page` (since all are in `Team` anyway)
* add the developers + info to `Contact`

**Comment by susheel** [comment]
Fixed with pull request #12
