### ISSUE TITLE
Add links to related projects, resources, implementations

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/ga4gh-beacon-legacy-website#13]
IMO  we should have a first level page for Links + descriptions to relevant external resources & implementations. Examples

* Beacon network page
* EGA Beacon
* our Beacon+ (beacon.progenetix.org), which demonstrates CNV queries etc.
* ICGC Beacon
* ...

**Comment by mcupak** [comment]
BTW, there's a list on the specification wiki: https://github.com/ga4gh-beacon/specification/wiki/Resources
