### ISSUE TITLE
Need to redirect beacon project domain name to Github Page on Website release

### ISSUE THREAD

**Issue by susheel** [ga4gh-beacon/ga4gh-beacon-legacy-website#2]
- [x] Purchase/Procure appropriate domain name for Beacon project
- [x] Update GH-Page CNAME for domain redirection

**Comment by mbaudis** [comment]
Can't we use any of:
* beacon.elixir-europe.org (may collide with possible? future ELIXIR beacon implementations...)
* beacon-project.elixir-europe.org (bit unwieldy for my taste)
...

We can also have __anything__.ga4ghdata.org_ (one of my domains).

¿¿¿ ga4ghprojects.org ???

**Comment by susheel** [comment]
NEW Beacon Project Domain: beacon-project.io

**Comment by mbaudis** [comment]
Great - thanks, Susheel!

Michael.
