### ISSUE TITLE
Update how to light a ELIXIR Beacon documentation

### ISSUE THREAD

**Issue by juhtornr** [ga4gh-beacon/ga4gh-beacon-legacy-website#20]
@juhtornr commented on [Tue Feb 27 2018](https://github.com/ga4gh-beacon/specification/issues/129)

**Comment by mcupak** [comment]
https://github.com/ga4gh-beacon/specification/issues/129#issuecomment-378255259

**Comment by sdelatorrep** [comment]
Shouldn't this issue be in the beacon-elixir repository?

**Comment by mcupak** [comment]
@sdelatorrep You're right, something is broken about this issue, there are duplicates too.

**Comment by mcupak** [comment]
Issue moved to [ga4gh-beacon/beacon-elixir #6](https://github.com/ga4gh-beacon/beacon-elixir/issues/6) via [**ZenHub**](https://www.zenhub.com/)
