### ISSUE TITLE
Update how to light a ELIXIR Beacon documentation

### ISSUE THREAD

**Issue by juhtornr** [ga4gh-beacon/ga4gh-beacon-legacy-website#21]
@juhtornr commented on [Tue Feb 27 2018](https://github.com/ga4gh-beacon/specification/issues/129)

---

@juhtornr commented on [Wed Mar 07 2018](https://github.com/ga4gh-beacon/specification/issues/129#issuecomment-371214072)

Issue moved to [ga4gh-beacon/ga4gh-beacon.github.io #20](https://github.com/ga4gh-beacon/ga4gh-beacon.github.io/issues/20) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mcupak** [comment]
Duplicate of #20.
