### ISSUE TITLE
Use SSL

### ISSUE THREAD

**Issue by mcupak** [ga4gh-beacon/ga4gh-beacon-legacy-website#24]
GitHub now has a setting, assuming the domain is configured:
![image](https://user-images.githubusercontent.com/1255598/40247725-570256de-5a9b-11e8-92f5-40d37c365df2.png)

**Comment by susheel** [comment]
@martin-nc For HTTPS to work for custom domains, please update DNS `A` records to point to:

- 185.199.108.153
- 185.199.109.153
- 185.199.110.153
- 185.199.111.153

**Comment by martin-nc** [comment]
The domain is managed by the EBI Web Production team. I've put the ticket in with them to get this done.

**Comment by martin-nc** [comment]
The DNS records have been updated. I've removed and re-added the domain to the repo, and it's all working for me over https.

**Comment by martin-nc** [comment]
Oh - I've also enforced https.

**Comment by mcupak** [comment]
Works like a charm, thank you!
