### ISSUE TITLE
Filters: Documenting "FuzzyFilters"

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/ga4gh-beacon-legacy-website#41]
The first version of the [Filters](https://github.com/ga4gh-beacon/ga4gh-beacon.github.io/blob/master/pages/_doc/v2-filters.md) document describes the `FuzzyFilters` class:

    `FuzzyFilters` are implementations of classifiers which allow for some alternatives in matching and mostly can be drop-ins where ontologies are incomplete.
    Logically, through the potential matching of multiple values they provide a limited alternative mechanism to allow `OR`-style queries.

This concept needs examples and possibly a schema (i.e. different filters and their use cases; regular expressions for individual FFs ...).

**Comment by jrambla** [comment]
In its initial view, the category "FuzzyFilters" was just a mechanism to tag filters that shouldn't be interpreted as exact matches, but that could be processed by the target server at its best will. 
The expectation is that the "semantics" in that section of the query mimics the MatchMaker Exchange approach as much as it makes sense.

**Comment by mbaudis** [comment]
@jrambla So do we now have a separate style of filter definitions, or a tagging system where filters are flagged for being "fuzzy"? Examples?
